spring:
  zipkin:
    baseUrl: http://zipkin:9411/            

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/   